language: java
addons:
  mariadb: '10.0'
jdk:
  - oraclejdk8
before_script:
  - mysql -e "use mysql; update user set password=PASSWORD('123456') where User='root'; flush privileges;" -uroot
  - mysql -uroot -p123456 < travis-resources/unielwin_course.sql
  - mysql -uroot -p123456 < travis-resources/unielwin_prof.sql
  - mysql -uroot -p123456 < travis-resources/unielwin_RA.sql
  - mysql -uroot -p123456 < travis-resources/unielwin_registration.sql
  - mysql -uroot -p123456 < travis-resources/unielwin_student.sql
  - mysql -uroot -p123456 < travis-resources/tests-database.sql
script:
  - cd code
  - mvn install -DtestDBUserName=root -DtestDBPassword=123456
  - java -Dconfig=../travis-resources/config.cfg -jar factorbase/target/factorbase*SNAPSHOT.jar
  - ls -lh
  - tail dag_.txt
  - java -Dconfig=../travis-resources/config.cfg -jar mlnexporter/target/mlnexporter*SNAPSHOT.jar > mln_jar.txt
  - tail mln_jar.txt

after_script:
  - mysql -e "show databases;" -uroot -p123456
  - mysql -e "use unielwin_BN; show tables;" -uroot -p123456
  - mysql -e "use unielwin_CT; show tables;" -uroot -p123456